// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmeljufpsqssalexazle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZWxqdWZwc3Fzc2FsZXhhemxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTk5MTcsImV4cCI6MjA2OTczNTkxN30.3o9Gi1LZ8rdJBoHASlCUgkX02ISjtEGR9gT6j8p34D0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});